server:
  port: 8080
logging:
  level:
    web: trace
    org:
      springframework:
        web:
          client: trace


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-oidc:
            provider: keycloak
            client-name: bugtracker
            client-id: bugtracker
            client-secret: GCtEu85aLJA8TQMucq9cXo7BpZ5Ze2NO
#            client-authentication-method: none
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:9090/realms/oauthrealm

# This represents the Keycloak Provider (issuer is enough for Spring Boot to know all endpoints)
# Openid configuration - http://127.0.0.1:9090/realms/oauthrealm/.well-known/openid-configuration